/*
 * Automatically generated by 'ng g ng-alain:plugin icon'
 */

import {
  ArrowDownOutline,
  CopyrightOutline,
  DingtalkOutline,
  DownloadOutline,
  EyeInvisibleOutline,
  FullscreenExitOutline,
  FullscreenOutline,
  GithubOutline,
  LockOutline,
  LogoutOutline,
  MailOutline,
  SettingOutline,
  ToolOutline,
  UserOutline
} from '@ant-design/icons-angular/icons';

export const ICONS_AUTO = [
  ArrowDownOutline,
  CopyrightOutline,
  DingtalkOutline,
  DownloadOutline,
  EyeInvisibleOutline,
  FullscreenExitOutline,
  FullscreenOutline,
  GithubOutline,
  LockOutline,
  LogoutOutline,
  MailOutline,
  SettingOutline,
  ToolOutline,
  UserOutline
];
